const { fromExtendedKey } = require("ethers/utils/hdnode");

module.exports = function () {
    let start, end;
    start = (new Date()).getTime();
    fromExtendedKey("xpub6E7BR59KtqbeZg98VGEBAtgBb6MPw3xsVnF9TQQyRpFBerY4LJvotYajhT9UFEHB78Q1BCZQATNGi5A3FhJZxRMcwo3mwpJyRp6NePvEoFo").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6EQJxHtLmMyJ9H4wRNhEe4J1PJB8WbMBa3VBh5XzM37p7DZhXbLBnbXtWzxDz5r5k9Roq8SQsAvYCbxhvGRkjfPVSb6BQqFcuUAi6M5rBxv").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6EQJxHtLmMyJ9H4wRNhEe4J1PJB8WbMBa3VBh5XzM37p7DZhXbLBnbXtWzxDz5r5k9Roq8SQsAvYCbxhvGRkjfPVSb6BQqFcuUAi6M5rBxv").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6E7BR59KtqbeZg98VGEBAtgBb6MPw3xsVnF9TQQyRpFBerY4LJvotYajhT9UFEHB78Q1BCZQATNGi5A3FhJZxRMcwo3mwpJyRp6NePvEoFo").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6EQJxHtLmMyJ9H4wRNhEe4J1PJB8WbMBa3VBh5XzM37p7DZhXbLBnbXtWzxDz5r5k9Roq8SQsAvYCbxhvGRkjfPVSb6BQqFcuUAi6M5rBxv").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6E7BR59KtqbeZg98VGEBAtgBb6MPw3xsVnF9TQQyRpFBerY4LJvotYajhT9UFEHB78Q1BCZQATNGi5A3FhJZxRMcwo3mwpJyRp6NePvEoFo").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6EQJxHtLmMyJ9H4wRNhEe4J1PJB8WbMBa3VBh5XzM37p7DZhXbLBnbXtWzxDz5r5k9Roq8SQsAvYCbxhvGRkjfPVSb6BQqFcuUAi6M5rBxv").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6E7BR59KtqbeZg98VGEBAtgBb6MPw3xsVnF9TQQyRpFBerY4LJvotYajhT9UFEHB78Q1BCZQATNGi5A3FhJZxRMcwo3mwpJyRp6NePvEoFo").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6E7BR59KtqbeZg98VGEBAtgBb6MPw3xsVnF9TQQyRpFBerY4LJvotYajhT9UFEHB78Q1BCZQATNGi5A3FhJZxRMcwo3mwpJyRp6NePvEoFo").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6EQJxHtLmMyJ9H4wRNhEe4J1PJB8WbMBa3VBh5XzM37p7DZhXbLBnbXtWzxDz5r5k9Roq8SQsAvYCbxhvGRkjfPVSb6BQqFcuUAi6M5rBxv").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6E7BR59KtqbeZg98VGEBAtgBb6MPw3xsVnF9TQQyRpFBerY4LJvotYajhT9UFEHB78Q1BCZQATNGi5A3FhJZxRMcwo3mwpJyRp6NePvEoFo").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6EQJxHtLmMyJ9H4wRNhEe4J1PJB8WbMBa3VBh5XzM37p7DZhXbLBnbXtWzxDz5r5k9Roq8SQsAvYCbxhvGRkjfPVSb6BQqFcuUAi6M5rBxv").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6E7BR59KtqbeZg98VGEBAtgBb6MPw3xsVnF9TQQyRpFBerY4LJvotYajhT9UFEHB78Q1BCZQATNGi5A3FhJZxRMcwo3mwpJyRp6NePvEoFo").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6EQJxHtLmMyJ9H4wRNhEe4J1PJB8WbMBa3VBh5XzM37p7DZhXbLBnbXtWzxDz5r5k9Roq8SQsAvYCbxhvGRkjfPVSb6BQqFcuUAi6M5rBxv").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6EQJxHtLmMyJ9H4wRNhEe4J1PJB8WbMBa3VBh5XzM37p7DZhXbLBnbXtWzxDz5r5k9Roq8SQsAvYCbxhvGRkjfPVSb6BQqFcuUAi6M5rBxv").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6FEMgxstJf9otmMfGKcm1MA2AGaSSee5Pcx1MGeL4pLJLVVSbWYQ9vEsavuihMXtfF1dX44ypagwBoULsS9hMVQqGRYWB5rYgPvcvfcLsKp").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6FEMgxstJf9otmMfGKcm1MA2AGaSSee5Pcx1MGeL4pLJLVVSbWYQ9vEsavuihMXtfF1dX44ypagwBoULsS9hMVQqGRYWB5rYgPvcvfcLsKp").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6EQJxHtLmMyJ9H4wRNhEe4J1PJB8WbMBa3VBh5XzM37p7DZhXbLBnbXtWzxDz5r5k9Roq8SQsAvYCbxhvGRkjfPVSb6BQqFcuUAi6M5rBxv").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6FEMgxstJf9otmMfGKcm1MA2AGaSSee5Pcx1MGeL4pLJLVVSbWYQ9vEsavuihMXtfF1dX44ypagwBoULsS9hMVQqGRYWB5rYgPvcvfcLsKp").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
    start = (new Date()).getTime();
    fromExtendedKey("xpub6EQJxHtLmMyJ9H4wRNhEe4J1PJB8WbMBa3VBh5XzM37p7DZhXbLBnbXtWzxDz5r5k9Roq8SQsAvYCbxhvGRkjfPVSb6BQqFcuUAi6M5rBxv").derivePath("0");
    end = (new Date()).getTime();
    console.log((end-start)/1000);
}
